"""VoxShield AI — Multi-Signal Threat Fusion & Decision Engine."""

from typing import List, Optional
from pydantic import BaseModel, Field

from app.ai.base import BaseAIComponent


class ThreatAssessment(BaseModel):
    """Holistic threat assessment generated by fusing multiple detection signals."""
    threat_score: float = Field(..., ge=0.0, le=100.0, description="Overall threat score (0-100)")
    severity: str = Field(..., description="LOW | MEDIUM | HIGH | CRITICAL")
    recommended_action: str = Field(
        ...,
        description="CONTINUE_NORMAL | DISPLAY_ADVISORY | REQUIRE_VERIFICATION | RECOMMEND_TERMINATION"
    )
    recommendation: str
    indicators: List[str] = Field(default_factory=list)
    breakdown: Optional[dict] = None


class ThreatFusionEngine(BaseAIComponent):
    """Multi-signal threat fusion combining deepfake, speaker similarity, and liveness signals.
    
    Weights:
    - Synthetic voice probability: 0.45
    - Speaker voiceprint mismatch: 0.30
    - Liveness / replay failure: 0.25
    
    Severity Thresholds:
    - LOW: 0 - 24.9
    - MEDIUM: 25.0 - 49.9
    - HIGH: 50.0 - 74.9
    - CRITICAL: 75.0 - 100.0
    """

    def __init__(
        self,
        weight_ai: float = 0.45,
        weight_speaker_mismatch: float = 0.30,
        weight_liveness_failure: float = 0.25,
        model_name: str = "VoxShield-ThreatFusion-v2",
        model_version: str = "fusion-v2.0",
        device: str = "cpu",
    ):
        super().__init__(
            model_name=model_name,
            model_version=model_version,
            device=device,
            engine_type="REAL_LOCAL_MODEL",
        )
        self.weight_ai = weight_ai
        self.weight_speaker_mismatch = weight_speaker_mismatch
        self.weight_liveness_failure = weight_liveness_failure

    def evaluate(
        self,
        ai_probability: float,
        speaker_match_score: Optional[float] = None,
        liveness_score: Optional[float] = None,
        is_claimed_trusted_contact: bool = False,
        anomaly_flags: Optional[List[str]] = None,
    ) -> ThreatAssessment:
        import math
        for val, name in [
            (ai_probability, "ai_probability"),
            (speaker_match_score, "speaker_match_score"),
            (liveness_score, "liveness_score"),
        ]:
            if val is not None and (math.isnan(val) or math.isinf(val)):
                raise ValueError(f"Invalid numeric input for {name}: NaN or Infinity not permitted")

        indicators: List[str] = []
        flags = anomaly_flags or []

        # 1. Base Deepfake AI component (0 to 100)
        p_ai = min(1.0, max(0.0, float(ai_probability)))
        score_ai = p_ai * 100.0
        if p_ai >= 0.70:
            indicators.append(f"High synthetic speech probability ({p_ai * 100:.1f}%)")
        elif p_ai >= 0.40:
            indicators.append(f"Ambiguous vocoder acoustic characteristics ({p_ai * 100:.1f}%)")

        # 2. Speaker Match component (0 to 100)
        if speaker_match_score is not None:
            s_match = min(1.0, max(0.0, float(speaker_match_score)))
            score_speaker = (1.0 - s_match) * 100.0
            if s_match < 0.60:
                indicators.append(f"Voice embedding mismatch ({s_match * 100:.1f}% similarity)")
        else:
            # Baseline neutral score when caller identity is unverified
            score_speaker = 20.0

        # 3. Liveness component (0 to 100)
        if liveness_score is not None:
            s_live = min(1.0, max(0.0, float(liveness_score)))
            score_liveness = (1.0 - s_live) * 100.0
            if s_live < 0.50:
                indicators.append("Liveness failure: Replay or synthetic acoustic traits detected")
        else:
            score_liveness = 15.0

        # Weighted calculation
        raw_score = (
            self.weight_ai * score_ai
            + self.weight_speaker_mismatch * score_speaker
            + self.weight_liveness_failure * score_liveness
        )

        # 4. Contextual Modifiers & Escalators
        modifier = 0.0

        # Impersonation Penalty: Claiming to be a trusted contact with poor match
        if is_claimed_trusted_contact and speaker_match_score is not None and speaker_match_score < 0.60:
            modifier += 20.0
            indicators.append("URGENT: Caller claims to be a trusted contact but voice embedding does not match")

        # Anomaly flags
        if "vocoder_phase_discontinuity" in flags:
            modifier += 10.0
            indicators.append("Phase discontinuity typical of zero-shot neural vocoders")

        if "replay_detected" in flags:
            modifier += 12.0
            indicators.append("Acoustic impulse response indicates loudspeaker replay")

        # Damping bonus: high liveness + very low AI prob
        if liveness_score is not None and liveness_score > 0.85 and p_ai < 0.10:
            modifier -= 8.0

        final_score = round(min(100.0, max(0.0, raw_score + modifier)), 1)

        # Severity & Progressive Mitigation
        if final_score >= 75.0:
            severity = "CRITICAL"
            action = "RECOMMEND_TERMINATION"
            rec = "CRITICAL THREAT: High-confidence voice clone impersonation attack. Hang up immediately."
        elif final_score >= 50.0:
            severity = "HIGH"
            action = "REQUIRE_VERIFICATION"
            rec = "HIGH SUSPICION: Voice characteristics indicate synthetic cloning. Verify via out-of-band channel."
        elif final_score >= 25.0:
            severity = "MEDIUM"
            action = "DISPLAY_ADVISORY"
            rec = "ADVISORY: Minor acoustic anomalies detected. Proceed with caution."
        else:
            severity = "LOW"
            action = "CONTINUE_NORMAL"
            rec = "NORMAL: Voice stream appears authentic."

        if not indicators:
            indicators.append("No significant anomalies observed.")

        breakdown = {
            "ai_component": round(score_ai, 1),
            "speaker_component": round(score_speaker, 1),
            "liveness_component": round(score_liveness, 1),
            "modifiers": round(modifier, 1),
        }

        return ThreatAssessment(
            threat_score=final_score,
            severity=severity,
            recommended_action=action,
            recommendation=rec,
            indicators=indicators,
            breakdown=breakdown,
        )


threat_fusion_engine = ThreatFusionEngine()
